### ISSUE TITLE
missing config option in --help

### ISSUE THREAD

**Issue by jason-weirather** [CIMAC-CIDC/cidc-cli#110]
I found in the source code how to configure from staging back to the main portal, but it would be nice if that was in the `--help` option.  argparse auto-generates this kind of help message if thats compatible how you're doing this.

**Comment by jacoblurye** [comment]
@jason-weirather - we deliberately hide the `config` option (see here: https://github.com/CIMAC-CIDC/cidc-cli/blob/e5c39d3847eeeb386d30f86ac270950215d4a5cf/cli/cli.py#L28), because we don't want the typical CLI user to interface with anything but the production API. That being said, we should make sure to more clearly document this option in any SOPs for people we expect to use the staging API.
